steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: tiag0ss/project-management
      tags: latest
      dockerfile: Dockerfile
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
    when:
      - event: push
        branch: main